spring.profiles.active=default

#logging.level.root=DEBUG


spring.application.name=InventoryService

server.port=9010
server.servlet.context-path=/api/v1

# Database Configuration Template
spring.datasource.url=jdbc:postgresql://localhost:5432/InventoryDB
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable SQL logging to the console (standard output)
spring.jpa.show-sql=true

# Pretty-print or format the SQL statements for readability
spring.jpa.properties.hibernate.format_sql=true

# CRITICAL: These loggers will ensure SQL appears in your console
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Data Initialization

spring.sql.init.data-locations=classpath:data.sql
spring.jpa.hibernate.ddl-auto=update

#eureka config
eureka.client.server-url.defaultZone=http://localhost:8761/eureka





